# Generated by Django 3.2.4 on 2022-09-10 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=80)),
                ('Email', models.CharField(max_length=40)),
                ('Mobile', models.CharField(max_length=30)),
                ('Msg', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='currentuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('passwd', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='lecturecat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('cpic', models.ImageField(null=True, upload_to='static/vcategory/')),
            ],
        ),
        migrations.CreateModel(
            name='myregister',
            fields=[
                ('rno', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('passwd', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=50)),
                ('pic', models.ImageField(null=True, upload_to='static/profile/')),
            ],
        ),
        migrations.CreateModel(
            name='studentanswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=100)),
                ('asid', models.CharField(max_length=100)),
                ('sremark', models.TextField()),
                ('sanswer', models.ImageField(null=True, upload_to='static/answerfile/')),
                ('marks', models.IntegerField()),
                ('submitdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='teacherreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('relcourse', models.CharField(max_length=100)),
                ('profilepic', models.ImageField(null=True, upload_to='static/teacherpic/')),
            ],
        ),
        migrations.CreateModel(
            name='ugallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gdes', models.CharField(max_length=200)),
                ('picture', models.ImageField(default='', upload_to='static/gallery/')),
            ],
        ),
        migrations.CreateModel(
            name='lecturevideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlink', models.CharField(max_length=300)),
                ('vtitle', models.CharField(max_length=200)),
                ('vdes', models.TextField()),
                ('vcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.lecturecat')),
            ],
        ),
        migrations.CreateModel(
            name='assignmenttbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atitle', models.CharField(max_length=200)),
                ('adesc', models.TextField()),
                ('course', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=100)),
                ('asub', models.CharField(max_length=100)),
                ('assigndate', models.DateField()),
                ('totalmarks', models.IntegerField()),
                ('lastdate', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('attachfile', models.FileField(null=True, upload_to='static/testfile/')),
                ('assignby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.teacherreg')),
            ],
        ),
    ]
